import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import * as ts from "typescript";

const defaultRoot = path.resolve(fileURLToPath(new URL("..", import.meta.url)));
const defaultOutput = "examples/basic/app/generated/api-reference.ts";

export interface ApiReferenceSymbol {
  readonly name: string;
  readonly kind: "function" | "class" | "interface" | "type" | "enum" | "variable" | "namespace";
  readonly signature: string;
  readonly summary: string;
  readonly deprecated: boolean;
  readonly examples: readonly string[];
  readonly source: string;
  readonly line: number;
}

export interface ApiReferenceEntry {
  readonly subpath: string;
  readonly importPath: string;
  readonly source: string;
  readonly symbols: readonly ApiReferenceSymbol[];
}

export interface ApiReferencePackage {
  readonly name: string;
  readonly version: string;
  readonly description: string;
  readonly readme: string | null;
  readonly entries: readonly ApiReferenceEntry[];
}

export interface ApiReferenceDocument {
  readonly version: 1;
  readonly generatedBy: "scripts/api-reference.ts";
  readonly packageVersion: string;
  readonly packages: readonly ApiReferencePackage[];
}

interface PackageManifest {
  readonly name: string;
  readonly version: string;
  readonly description?: string;
  readonly exports?: unknown;
  readonly bin?: Readonly<Record<string, string>>;
}

interface EntryTarget {
  readonly subpath: string;
  readonly target: string;
}

/** Creates a deterministic API reference from package exports and TypeScript declarations. */
export async function createApiReference(repositoryRoot = defaultRoot): Promise<ApiReferenceDocument> {
  const rootManifest = JSON.parse(await readFile(path.join(repositoryRoot, "package.json"), "utf8")) as { readonly version: string };
  const program = createProgram(repositoryRoot);
  const checker = program.getTypeChecker();
  const sourceFiles = new Map(program.getSourceFiles().map((source) => [normalize(source.fileName), source]));
  const packagesRoot = path.join(repositoryRoot, "packages");
  const directories = (await readdir(packagesRoot, { withFileTypes: true }))
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();
  const packages: ApiReferencePackage[] = [];

  for (const directory of directories) {
    const packageDirectory = path.join(packagesRoot, directory);
    const manifest = JSON.parse(await readFile(path.join(packageDirectory, "package.json"), "utf8")) as PackageManifest;
    const targets = manifest.exports === undefined
      ? Object.entries(manifest.bin ?? {}).map(([name, target]) => ({ subpath: `bin:${name}`, target }))
      : collectEntryTargets(manifest.exports);
    const entries: ApiReferenceEntry[] = [];

    for (const target of targets) {
      if (target.target.includes("*") || !/\.[cm]?[jt]sx?$/.test(target.target)) continue;
      const absolute = path.resolve(packageDirectory, target.target);
      const sourceFile = sourceFiles.get(normalize(absolute));
      const module = sourceFile ? checker.getSymbolAtLocation(sourceFile) : undefined;
      if (!sourceFile || !module) continue;
      const symbols = checker.getExportsOfModule(module)
        .map((exported) => describeSymbol(exported, checker, repositoryRoot, packagesRoot))
        .filter((symbol): symbol is ApiReferenceSymbol => symbol !== null)
        .sort((left, right) => left.name.localeCompare(right.name));
      entries.push({
        subpath: target.subpath,
        importPath: target.subpath === "." ? manifest.name : `${manifest.name}${target.subpath.slice(1)}`,
        source: relative(repositoryRoot, absolute),
        symbols,
      });
    }

    const readme = path.join(packageDirectory, "README.md");
    packages.push({
      name: manifest.name,
      version: manifest.version,
      description: manifest.description?.trim() || await readmeDescription(readme) || `${manifest.name} public API.`,
      readme: await exists(readme) ? relative(repositoryRoot, readme) : null,
      entries: entries.sort((left, right) => left.subpath.localeCompare(right.subpath)),
    });
  }

  return {
    version: 1,
    generatedBy: "scripts/api-reference.ts",
    packageVersion: rootManifest.version,
    packages: packages.sort((left, right) => left.name.localeCompare(right.name)),
  };
}

/** Renders the generated TypeScript module consumed by the server-first docs route. */
export function renderApiReferenceModule(document: ApiReferenceDocument): string {
  return `// Generated by scripts/api-reference.ts. Do not edit manually.\nexport const apiReference = ${JSON.stringify(document, null, 2)} as const;\n`;
}

/** Writes the canonical generated API reference module. */
export async function writeApiReference(repositoryRoot = defaultRoot): Promise<string> {
  const output = path.join(repositoryRoot, defaultOutput);
  await mkdir(path.dirname(output), { recursive: true });
  await writeFile(output, renderApiReferenceModule(await createApiReference(repositoryRoot)), "utf8");
  return output;
}

/** Fails when the checked-in API reference no longer matches public exports. */
export async function checkApiReference(repositoryRoot = defaultRoot): Promise<void> {
  const output = path.join(repositoryRoot, defaultOutput);
  const expected = renderApiReferenceModule(await createApiReference(repositoryRoot));
  let actual = "";
  try { actual = await readFile(output, "utf8"); } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
  }
  if (actual !== expected) throw new Error("Generated API reference is stale. Run npm run docs:api.");
}

function describeSymbol(
  exported: ts.Symbol,
  checker: ts.TypeChecker,
  repositoryRoot: string,
  packagesRoot: string,
): ApiReferenceSymbol | null {
  const symbol = exported.flags & ts.SymbolFlags.Alias ? checker.getAliasedSymbol(exported) : exported;
  const declaration = symbol.declarations?.find((candidate) => {
    const file = normalize(candidate.getSourceFile().fileName);
    return file.startsWith(`${normalize(packagesRoot)}/`) && !file.includes("/packages/icons/src/linear/") && !file.endsWith(".module.d.css.ts");
  });
  if (!declaration) return null;
  const name = exported.getName();
  if (name === "default") return null;
  const sourceFile = declaration.getSourceFile();
  const tags = symbol.getJsDocTags(checker);
  const summary = ts.displayPartsToString(symbol.getDocumentationComment(checker)).trim() || fallbackSummary(name, kindOf(symbol));
  return {
    name,
    kind: kindOf(symbol),
    signature: signatureOf(name, symbol, declaration, checker),
    summary,
    deprecated: tags.some(({ name: tag }) => tag === "deprecated"),
    examples: tags.filter(({ name: tag }) => tag === "example").map(({ text }) => text?.map(({ text: part }) => part).join("").trim() ?? "").filter(Boolean),
    source: relative(repositoryRoot, sourceFile.fileName),
    line: sourceFile.getLineAndCharacterOfPosition(declaration.getStart(sourceFile)).line + 1,
  };
}

function kindOf(symbol: ts.Symbol): ApiReferenceSymbol["kind"] {
  if (symbol.flags & ts.SymbolFlags.Function) return "function";
  if (symbol.flags & ts.SymbolFlags.Class) return "class";
  if (symbol.flags & ts.SymbolFlags.Interface) return "interface";
  if (symbol.flags & ts.SymbolFlags.TypeAlias) return "type";
  if (symbol.flags & ts.SymbolFlags.Enum) return "enum";
  if (symbol.flags & ts.SymbolFlags.NamespaceModule) return "namespace";
  return "variable";
}

function signatureOf(name: string, symbol: ts.Symbol, declaration: ts.Declaration, checker: ts.TypeChecker): string {
  const flags = ts.TypeFormatFlags.NoTruncation | ts.TypeFormatFlags.UseAliasDefinedOutsideCurrentScope | ts.TypeFormatFlags.MultilineObjectLiterals;
  if (symbol.flags & ts.SymbolFlags.Function) {
    const type = checker.getTypeOfSymbolAtLocation(symbol, declaration);
    const signatures = checker.getSignaturesOfType(type, ts.SignatureKind.Call);
    return signatures.length ? signatures.map((signature) => `${name}${checker.signatureToString(signature, declaration, flags)}`).join("\n") : `function ${name}`;
  }
  if (symbol.flags & ts.SymbolFlags.Enum) {
    const members = symbol.exports ? [...symbol.exports.keys()].map(String) : [];
    return `enum ${name}${members.length ? ` { ${members.join(", ")} }` : ""}`;
  }
  const type = symbol.flags & (ts.SymbolFlags.Class | ts.SymbolFlags.Interface | ts.SymbolFlags.TypeAlias)
    ? checker.getDeclaredTypeOfSymbol(symbol)
    : checker.getTypeOfSymbolAtLocation(symbol, declaration);
  const label = kindOf(symbol);
  if (label === "class" || label === "interface") {
    const typeParameters = (ts.isClassDeclaration(declaration) || ts.isInterfaceDeclaration(declaration))
      ? declaration.typeParameters?.map((parameter) => parameter.getText()).join(", ")
      : undefined;
    const members = checker.getPropertiesOfType(type).map((member) => {
      const memberDeclaration = member.valueDeclaration ?? member.declarations?.[0] ?? declaration;
      const optional = member.flags & ts.SymbolFlags.Optional ? "?" : "";
      return `${member.getName()}${optional}: ${checker.typeToString(checker.getTypeOfSymbolAtLocation(member, memberDeclaration), memberDeclaration, flags)}`;
    });
    return `${label} ${name}${typeParameters ? `<${typeParameters}>` : ""}${members.length ? ` {\n  ${members.join(";\n  ")}\n}` : ""}`;
  }
  const rendered = ts.isTypeAliasDeclaration(declaration)
    ? checker.typeToString(checker.getTypeFromTypeNode(declaration.type), declaration, flags)
    : checker.typeToString(type, declaration, flags);
  return `${label} ${name}${rendered === name ? "" : ` = ${rendered}`}`;
}

function fallbackSummary(name: string, kind: ApiReferenceSymbol["kind"]): string {
  return `Public ${kind} ${name} exported by CocoFrame.`;
}

function createProgram(repositoryRoot: string): ts.Program {
  const configPath = path.join(repositoryRoot, "tsconfig.json");
  const config = ts.readConfigFile(configPath, ts.sys.readFile);
  if (config.error) throw new Error(ts.flattenDiagnosticMessageText(config.error.messageText, "\n"));
  const parsed = ts.parseJsonConfigFileContent(config.config, ts.sys, repositoryRoot, undefined, configPath);
  return ts.createProgram({ rootNames: parsed.fileNames, options: parsed.options });
}

function collectEntryTargets(value: unknown, subpath = "."): EntryTarget[] {
  if (typeof value === "string") return [{ subpath, target: value }];
  if (!value || typeof value !== "object" || Array.isArray(value)) return [];
  const record = value as Readonly<Record<string, unknown>>;
  const subpaths = Object.keys(record).filter((key) => key.startsWith("."));
  if (subpaths.length) return subpaths.flatMap((key) => collectEntryTargets(record[key], key));
  for (const condition of ["types", "default", "import", "node"]) if (condition in record) return collectEntryTargets(record[condition], subpath);
  const first = Object.values(record)[0];
  return first === undefined ? [] : collectEntryTargets(first, subpath);
}

async function readmeDescription(file: string): Promise<string> {
  if (!(await exists(file))) return "";
  const paragraphs = (await readFile(file, "utf8")).replace(/^#.*$/m, "").trim().split(/\r?\n\r?\n/);
  return paragraphs.find((paragraph) => paragraph.trim() && !paragraph.trim().startsWith("```"))?.replace(/\s+/g, " ").trim() ?? "";
}

async function exists(file: string): Promise<boolean> {
  try { await readFile(file); return true; } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return false; throw error; }
}

function relative(root: string, file: string): string { return path.relative(root, file).replaceAll("\\", "/"); }
function normalize(file: string): string { return path.resolve(file).replaceAll("\\", "/").toLowerCase(); }

async function main(): Promise<void> {
  if (process.argv.includes("--check")) {
    await checkApiReference(defaultRoot);
    process.stdout.write("Generated API reference is current.\n");
    return;
  }
  const output = await writeApiReference(defaultRoot);
  process.stdout.write(`Generated API reference: ${relative(defaultRoot, output)}\n`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href) await main();
