import { defineIsland, signal } from "@cocoframe/client";
import type { CocoNode } from "@cocoframe/jsx";
import { sortComponentCatalogEntries } from "../components/component-navigation.ts";
import AddCircleIcon from "@cocoframe/icons/linear/add-circle";
import AlignHorizontalCenterIcon from "@cocoframe/icons/linear/align-horizontal-center";
import AlignLeftIcon from "@cocoframe/icons/linear/align-left";
import AlignRightIcon from "@cocoframe/icons/linear/align-right";
import ArrowUpIcon from "@cocoframe/icons/linear/arrow-up";
import BellIcon from "@cocoframe/icons/linear/bell";
import BoxMinimalisticIcon from "@cocoframe/icons/linear/box-minimalistic";
import CalendarIcon from "@cocoframe/icons/linear/calendar";
import CameraIcon from "@cocoframe/icons/linear/camera";
import ChatRoundIcon from "@cocoframe/icons/linear/chat-round";
import CheckCircleIcon from "@cocoframe/icons/linear/check-circle";
import CloseCircleIcon from "@cocoframe/icons/linear/close-circle";
import CodeSquareIcon from "@cocoframe/icons/linear/code-square";
import DocumentIcon from "@cocoframe/icons/linear/document";
import FolderIcon from "@cocoframe/icons/linear/folder";
import HamburgerMenuIcon from "@cocoframe/icons/linear/hamburger-menu";
import HeartIcon from "@cocoframe/icons/linear/heart";
import HomeIcon from "@cocoframe/icons/linear/home";
import LetterIcon from "@cocoframe/icons/linear/letter";
import MagnifierIcon from "@cocoframe/icons/linear/magnifier";
import MapPointIcon from "@cocoframe/icons/linear/map-point";
import PenIcon from "@cocoframe/icons/linear/pen";
import QuestionCircleIcon from "@cocoframe/icons/linear/question-circle";
import SettingsIcon from "@cocoframe/icons/linear/settings";
import StarIcon from "@cocoframe/icons/linear/star";
import TrashBinMinimalisticIcon from "@cocoframe/icons/linear/trash-bin-minimalistic";
import UserIcon from "@cocoframe/icons/linear/user";
import UsersGroupRoundedIcon from "@cocoframe/icons/linear/users-group-rounded";
import Widget4Icon from "@cocoframe/icons/linear/widget-4";
import {
  Accordion, Alert, AlertDialog, AppShell, AspectRatio, Attachment, Avatar, Badge, BottomNavigation, BottomSheet, Breadcrumb, Bubble,
  Button, ButtonGroup, Calendar, Card, Carousel, Chart, Checkbox, Code, Collapsible, Combobox, Command,
  Citation, Container, ContextMenu, DataTable, DatePicker, DateRangePicker, Details, Dialog, Direction, Divider, DropdownMenu, EmptyState,
  FileUpload, FilterBar, FormField, Grid, Heading, HoverCard, IconButton, IconInput, Inline, Input, InputGroup, InputOtp,
  Item, Kbd, Label, LiveRegion, Marker, MegaMenu, Menubar, Message, MessageScroller, MultiSelect, NavigationMenu,
  NumberField, Offcanvas, PageHeader, Pagination, Popover, Progress, PromptComposer, Questionnaire, RadioGroup,
  Resizable, SafeArea, ScrollArea, SearchField, Select, Sidebar, SiteHeader, Skeleton, SkipLink, Slider, Spinner,
  Stack, Stat, Stepper, Switch, SyntaxHighlighter, Table, Tabs, Text, Textarea, Theme, ThinkingIndicator, Toast,
  Toaster, Toggle, ToggleGroup, Toolbar, Tooltip, TreeView, VisuallyHidden,
} from "@cocoframe/ui";

interface PreviewContext {
  readonly activeTab: string;
  readonly toastVisible: boolean;
  readonly dataTableSortKey: string;
  readonly dataTableSortDirection: "asc" | "desc";
  readonly activateTab: (id: string) => void;
  readonly showToast: () => void;
  readonly hideToast: () => void;
  readonly sortDataTable: (key: string, direction: "asc" | "desc") => void;
}

interface ComponentEntry {
  readonly id: string;
  readonly name: string;
  readonly category: string;
  readonly description: string;
  readonly keywords: string;
  readonly props: readonly (readonly [string, string, string])[];
  readonly code: string;
  readonly preview: (context: PreviewContext) => CocoNode;
  readonly importCode?: string;
}

const chartLabels = ["Jan", "Feb", "Mar", "Apr", "May", "Jun"] as const;
const chartSeries = [
  { label: "Requests", data: [42, 68, 54, 88, 76, 104], tone: "primary" as const },
  { label: "Conversions", data: [24, 38, 31, 46, 52, 61], tone: "blue" as const },
] as const;
const chartBreakdown = [{ label: "Traffic", data: [48, 27, 16, 9] }] as const;
const chartBreakdownLabels = ["Organic", "Direct", "Referral", "Social"] as const;
const chartPoints = [
  { label: "Mobile", data: [{ x: 12, y: 24, r: 8, label: "A" }, { x: 26, y: 43, r: 13, label: "B" }, { x: 48, y: 37, r: 9, label: "C" }], tone: "primary" as const },
  { label: "Desktop", data: [{ x: 19, y: 51, r: 11, label: "D" }, { x: 39, y: 67, r: 17, label: "E" }, { x: 63, y: 58, r: 7, label: "F" }], tone: "violet" as const },
] as const;

const unorderedEntries: readonly ComponentEntry[] = [
  entry("theme", "Theme", "FOUNDATION", "A light, dark, or system boundary that switches every semantic token without changing component APIs.", "theme dark mode light system color scheme", [["theme", '"light" | "dark" | "system"', '"system"'], ["as", '"div" | "section" | "main"', '"div"']], '<Theme theme="dark"><Card>Dark surface</Card></Theme>', () => <Theme theme="dark" class="component-mini-surface"><Stack gap="small"><Heading level={3} size="small">Dark theme</Heading><Text tone="muted" size="small">Semantic tokens remain consistent.</Text><Button size="small">Continue</Button></Stack></Theme>),
  entry("skip-link", "SkipLink", "ACCESSIBILITY", "A skip-navigation link that appears on keyboard focus and moves directly to the main content.", "accessibility keyboard skip focus main", [["href", "string", '"#main"'], ["label", "string", '"Skip to main content"']], '<SkipLink href="#main" />', () => <div class="component-mini-surface"><SkipLink href="#skip-link-preview">Skip preview navigation</SkipLink><div id="skip-link-preview"><Text size="small">Press Tab to reveal the skip link.</Text></div></div>),
  entry("live-region", "LiveRegion", "ACCESSIBILITY", "A typed announcement region for async statuses, errors, loading, and UI updates.", "accessibility aria live status alert busy", [["politeness", '"polite" | "assertive" | "off"', '"polite"'], ["atomic / busy", "boolean", "true / false"]], '<LiveRegion politeness="polite">3 results loaded.</LiveRegion>', () => <Stack gap="small"><LiveRegion>3 projects loaded.</LiveRegion><LiveRegion politeness="assertive">Connection lost.</LiveRegion></Stack>),
  entry("safe-area", "SafeArea", "LAYOUT", "An inset boundary for notches, home indicators, and edge-to-edge mobile screens using safe-area environment variables.", "mobile safe area notch inset ios", [["edges", "SafeAreaEdge[]", "all edges"], ["as", "semantic element", '"div"']], '<SafeArea edges={["bottom"]}>Mobile actions</SafeArea>', () => <SafeArea edges={["top", "right", "bottom", "left"]} class="component-mini-surface"><Text size="small">Content respects every safe-area inset.</Text></SafeArea>),
  entry("app-shell", "AppShell", "LAYOUT", "A responsive application shell with header, sidebar, main content, footer, and mobile navigation.", "app shell dashboard layout responsive mobile", [["header / sidebar / footer", "CocoNode", "—"], ["mobileNavigation", "CocoNode", "—"], ["mainId / contentAs", "string / main|div", '"main" / "main"']], '<AppShell header={header} sidebar={sidebar} mobileNavigation={bottomNav}>...</AppShell>', () => <AppShell contentAs="div" mainId="app-shell-preview" class="component-app-shell-preview" header={<strong>Workspace</strong>} sidebar={<Text size="small">Navigation</Text>} mobileNavigation={<BottomNavigation items={[{ label: "Home", href: "#app-shell", current: true }, { label: "Projects", href: "#app-shell" }]} />}><Card><Text size="small">Responsive application content</Text></Card></AppShell>),
  entry("page-header", "PageHeader", "LAYOUT", "A ready-to-use page header with hierarchy, breadcrumb slot, description, and responsive actions.", "page header title actions breadcrumb layout", [["title", "string", "required"], ["eyebrow / description", "string", "—"], ["actions / breadcrumbs", "CocoNode", "—"]], '<PageHeader title="Projects" description="Manage every deployment." actions={<Button>New project</Button>} />', () => <PageHeader title="Projects" eyebrow="Workspace" description="Manage every deployment from one place." actions={<Button size="small">New project</Button>} />),
  entry("toolbar", "Toolbar", "LAYOUT", "An accessible action toolbar with start/end slots, wrapping, and sticky behavior.", "toolbar actions filter sticky responsive", [["label", "string", '"Page actions"'], ["start / end", "CocoNode", "—"], ["sticky / wrap", "boolean", "false / true"]], '<Toolbar start={<Button>Edit</Button>} end={<Button>Publish</Button>} />', () => <Toolbar start={<><Button size="small" variant="secondary">Edit</Button><Button size="small" variant="ghost">Duplicate</Button></>} end={<Button size="small">Publish</Button>} />),
  entry("filter-bar", "FilterBar", "FORM", "A server-friendly filter form with search role, filters, actions, and a live result count.", "filter bar search toolbar results form", [["filters", "CocoNode", "required"], ["actions / results", "CocoNode", "—"], ["method", '"get" | "post"', '"get"']], '<FilterBar filters={<SearchField id="q" name="q" label="Search" />} actions={<Button>Apply</Button>} />', () => <FilterBar filters={<><SearchField id="catalog-filter" name="q" label="Search projects" placeholder="Search projects…" /><Select id="catalog-status" name="status"><option>All statuses</option><option>Ready</option></Select></>} actions={<Button size="small">Apply</Button>} results={<span>24 projects</span>} />),
  entry("number-field", "NumberField", "FORM", "A typed number input with min/max/step, shared control sizes, label, hint, and a mobile numeric keyboard.", "number field quantity currency min max step", [["id / name / label", "string", "required"], ["value / min / max / step", "number", "—"], ["size", "ControlSize", '"medium"']], '<NumberField id="seats" name="seats" label="Team seats" min={1} max={100} />', () => <NumberField id="catalog-seats" name="seats" label="Team seats" value={12} min={1} max={100} hint="Between 1 and 100 seats." />),
  entry("multi-select", "MultiSelect", "FORM", "An accessible native multi-select for multiple choices without requiring a browser runtime.", "multi select tags multiple options", [["id / name / label", "string", "required"], ["options", "MultiSelectOption[]", "required"], ["value", "string[]", "[]"]], '<MultiSelect id="roles" name="roles" label="Roles" options={roles} value={["admin"]} />', () => <MultiSelect id="catalog-roles" name="roles" label="Team roles" value={["developer", "designer"]} hint="Use Ctrl/Cmd to select multiple." options={[{ label: "Developer", value: "developer" }, { label: "Designer", value: "designer" }, { label: "Product manager", value: "product" }, { label: "QA engineer", value: "qa" }]} />),
  entry("date-range-picker", "DateRangePicker", "DATE & TIME", "Two date controls in a semantic fieldset with linked start/end constraints.", "date range start end booking period", [["id / name / label", "string", "required"], ["start / end / min / max", "ISO date string", "—"], ["required / disabled", "boolean", "false"]], '<DateRangePicker id="period" name="period" label="Reporting period" start="2026-08-01" end="2026-08-31" />', () => <DateRangePicker id="catalog-period" name="period" label="Reporting period" start="2026-08-01" end="2026-08-31" />),
  entry("stepper", "Stepper", "NAVIGATION", "Horizontal or vertical step progress with complete/current/upcoming/error states.", "stepper wizard progress checkout onboarding", [["items", "StepperItem[]", "required"], ["orientation", '"horizontal" | "vertical"', '"horizontal"']], '<Stepper items={[{ id: "account", label: "Account", state: "complete" }, { id: "profile", label: "Profile", state: "current" }]} />', () => <Stepper items={[{ id: "account", label: "Account", description: "Complete", state: "complete" }, { id: "profile", label: "Profile", description: "In progress", state: "current" }, { id: "review", label: "Review", description: "Upcoming" }]} />),
  entry("tree-view", "TreeView", "NAVIGATION", "Server-first hierarchical navigation with native disclosure, current state, icons, and badges.", "tree view files hierarchy navigation folders", [["items", "TreeItem[]", "required"], ["label", "string", '"Tree navigation"']], '<TreeView items={[{ id: "app", label: "app", expanded: true, children: routes }]} />', () => <TreeView label="Project files" items={[{ id: "app", label: "app", icon: <FolderIcon size={17} />, expanded: true, children: [{ id: "routes", label: "routes", icon: <FolderIcon size={17} />, expanded: true, children: [{ id: "index", label: "index.page.tsx", href: "#tree-view", current: true }] }, { id: "components", label: "components", icon: <FolderIcon size={17} /> }] }]} />),
  entry("bottom-navigation", "BottomNavigation", "NAVIGATION", "Touch-friendly mobile navigation with icons, labels, badges, current state, and fixed safe-area mode.", "mobile bottom navigation tabs app bar safe area", [["items", "BottomNavigationItem[]", "required"], ["fixed", "boolean", "false"], ["label", "string", "mobile navigation"]], '<BottomNavigation items={navigation} fixed />', () => <BottomNavigation items={[{ label: "Home", href: "#bottom-navigation", icon: <HomeIcon size={20} />, current: true }, { label: "Projects", href: "#bottom-navigation", icon: <Widget4Icon size={20} /> }, { label: "Alerts", href: "#bottom-navigation", icon: <BellIcon size={20} />, badge: "3" }, { label: "Profile", href: "#bottom-navigation", icon: <UserIcon size={20} /> }]} />),
  entry("prompt-composer", "PromptComposer", "AI & CHAT", "A server-friendly AI prompt form with attachment slot, actions, hint, submit, disabled, and busy states.", "ai prompt composer chat input attachment send", [["id", "string", "required"], ["attachments / actions / submit", "CocoNode", "—"], ["busy / disabled", "boolean", "false"]], '<PromptComposer id="prompt" attachments={<Attachment items={files} />} actions={<Button>Attach</Button>} />', () => <PromptComposer id="catalog-prompt" placeholder="Ask Coco AI…" hint="AI can make mistakes. Review generated code." actions={<IconButton label="Attach file"><FolderIcon size={18} /></IconButton>} submit={<Button size="small">Send</Button>} />),
  entry("thinking-indicator", "ThinkingIndicator", "AI & CHAT", "An AI loading status with a screen-reader label, animated dots, and reduced-motion fallback.", "ai thinking loading streaming status", [["label", "string", '"AI is thinking"']], '<ThinkingIndicator label="Coco AI is thinking" />', () => <ThinkingIndicator label="Coco AI is reasoning" />),
  entry("citation", "Citation", "AI & CHAT", "A compact citation chip with source number, title, origin, link, and accessible name.", "ai citation source reference grounding", [["index / href / title", "number / string", "required"], ["source", "string", "—"]], '<Citation index={1} href="/docs" title="CocoFrame Docs" source="cocoframe.dev" />', () => <Inline gap="small"><Citation index={1} href="#citation" title="Rendering architecture" source="CocoFrame Docs" /><Citation index={2} href="#citation" title="Web standards" source="MDN" /></Inline>),
  entry("button", "Button", "ACTION", "A semantic button with four sizes, four visual variants, form behavior, and a disabled state.", "action submit reset ghost size small medium large xlarge", [["variant", '"primary" | "secondary" | "ghost" | "danger"', '"primary"'], ["size", "ControlSize", '"medium"'], ["type / disabled", "button type / boolean", '"button" / false']], `<Button size="small">Small</Button>\n<Button size="medium">Medium</Button>\n<Button size="large">Large</Button>\n<Button size="xlarge">Extra large</Button>`, () => <div class="component-size-showcase"><Button size="small">Small</Button><Button>Medium</Button><Button size="large">Large</Button><Button size="xlarge">Extra large</Button></div>),
  entry("icon-button", "IconButton", "ACTION", "An icon button with a required accessible name, four sizes, and four variants.", "icon action compact accessible size", [["label", "string", "required"], ["size", "ControlSize", '"medium"'], ["variant", "Button variant", '"ghost"']], `import SettingsIcon from "@cocoframe/icons/linear/settings";\n\n<IconButton label="Settings" size="xlarge"><SettingsIcon size={22} /></IconButton>`, () => <Inline gap="small" align="end"><IconButton label="Small add" size="small" variant="primary"><AddCircleIcon size={16} /></IconButton><IconButton label="Medium settings" variant="secondary"><SettingsIcon size={19} /></IconButton><IconButton label="Large edit" size="large"><PenIcon size={21} /></IconButton><IconButton label="Extra large delete" size="xlarge" variant="danger"><TrashBinMinimalisticIcon size={23} /></IconButton></Inline>),
  entry("input", "Input", "FORM", "A typed input with four consistent sizes, mobile-friendly behavior, and accessible validation support.", "email password search tel url number size", [["id / name", "string", "required"], ["type", '"text" | "email" | …', '"text"'], ["size", "ControlSize", '"medium"']], `<Input id="email" name="email" size="large" placeholder="you@example.com" />`, () => <Stack gap="small"><Input id="input-small" name="small" size="small" placeholder="Small input" /><Input id="input-medium" name="medium" placeholder="Medium input" /><Input id="input-large" name="large" size="large" placeholder="Large input" /><Input id="input-xlarge" name="xlarge" size="xlarge" placeholder="Extra-large input" /></Stack>),
  entry("search-field", "SearchField", "FORM", "A ready-to-use search input with a screen-reader label, icon, and four sizes.", "search query filter size", [["id / name / label", "string", "required"], ["size", "ControlSize", '"medium"'], ["value / placeholder", "string", "—"]], `<SearchField id="docs-search" name="q" label="Search docs" size="large" />`, () => <Stack gap="small"><SearchField id="search-small" name="small" label="Small search" size="small" placeholder="Small search" /><SearchField id="search-large" name="large" label="Large search" size="large" placeholder="Large search" /></Stack>),
  entry("icon-input", "IconInput", "FORM", "A ready-to-use input with an accessible leading icon, trailing icon, or trailing action.", "form icon leading trailing password clear", [["leadingIcon / trailingIcon", "CocoNode", "—"], ["trailingLabel", "string", '"Input action"'], ["size", "ControlSize", '"medium"']], `import LetterIcon from "@cocoframe/icons/linear/letter";\nimport CheckCircleIcon from "@cocoframe/icons/linear/check-circle";\n\n<IconInput id="email" name="email" type="email" leadingIcon={<LetterIcon size={18} />} trailingIcon={<CheckCircleIcon size={18} />} />`, () => <Stack gap="small"><IconInput id="icon-email" name="email" type="email" leadingIcon={<LetterIcon size={18} />} trailingIcon={<CheckCircleIcon size={18} />} placeholder="you@example.com" /><IconInput id="icon-search" name="search" size="large" leadingIcon={<MagnifierIcon size={20} />} trailingIcon={<CloseCircleIcon size={20} />} trailingLabel="Clear search" placeholder="Search projects..." /></Stack>),
  entry("input-group", "InputGroup", "FORM", "Combines an input with a prefix or suffix such as currency, domain, unit, or text action.", "input group addon prefix suffix currency url", [["start / end", "CocoNode", "—"], ["size", "ControlSize", '"medium"'], ["children", "Input", "required"]], `<InputGroup start="$" end="USD"><Input id="price" name="price" type="number" /></InputGroup>`, () => <Stack gap="small"><InputGroup start="https://" end=".com"><Input id="domain" name="domain" placeholder="your-domain" /></InputGroup><InputGroup start="$" end="USD" size="large"><Input id="price" name="price" type="number" size="large" placeholder="0.00" /></InputGroup></Stack>),
  entry("textarea", "Textarea", "FORM", "A resizable text area with four sizes and the same validation states as Input.", "message rows multiline size", [["id / name", "string", "required"], ["size", "ControlSize", '"medium"'], ["rows / placeholder", "number / string", "—"]], `<Textarea id="message" name="message" size="large" rows={5} />`, () => <Textarea id="component-message" name="message" size="large" rows={4} placeholder="Large message field..." />),
  entry("select", "Select", "FORM", "A native select with four lightweight, keyboard-friendly sizes that are easy to process on the server.", "option dropdown multiple size", [["id / name", "string", "required"], ["size", "ControlSize", '"medium"'], ["multiple", "boolean", "false"]], `<Select id="country" name="country" size="large">\n  <option value="id">Indonesia</option>\n</Select>`, () => <Stack gap="small"><Select id="select-small" name="small" size="small"><option>Small select</option></Select><Select id="select-xlarge" name="xlarge" size="xlarge"><option>Extra-large select</option></Select></Stack>),
  entry("checkbox", "Checkbox", "FORM", "A labeled checkbox with a description and automatic aria-describedby association.", "boolean consent terms", [["id / name / label", "string", "required"], ["description", "string", "—"], ["checked / required", "boolean", "false"]], `<Checkbox id="terms" name="terms" label="Accept terms" description="Required to continue." />`, () => <Checkbox id="component-terms" name="terms" label="Accept terms" description="You can review the terms before continuing." checked />),
  entry("radio-group", "RadioGroup", "FORM", "A radio fieldset with four sizes, legend, description, orientation, and disabled state.", "radio choice options fieldset size", [["id / name / legend", "string", "required"], ["options", "readonly RadioOption[]", "required"], ["orientation / size", 'orientation / ControlSize', '"vertical" / "medium"']], `<RadioGroup id="plan" name="plan" legend="Choose a plan" size="large" options={plans} />`, () => <RadioGroup id="component-plan" name="plan" legend="Choose a plan" description="You can change this later." value="pro" orientation="horizontal" size="large" options={[{ label: "Starter", value: "starter", description: "For personal projects" }, { label: "Pro", value: "pro", description: "For growing teams" }]} />),
  entry("switch", "Switch", "FORM", "A native-checkbox-based toggle with switch role and four consistent sizes.", "toggle switch boolean setting size", [["id / name / label", "string", "required"], ["size", "ControlSize", '"medium"'], ["checked / disabled", "boolean", "false"]], `<Switch id="updates" name="updates" label="Product updates" size="large" checked />`, () => <div class="component-size-showcase component-size-showcase--vertical"><Switch id="switch-small" name="small" label="Small" size="small" checked /><Switch id="switch-medium" name="medium" label="Medium" checked /><Switch id="switch-large" name="large" label="Large" size="large" checked /><Switch id="switch-xlarge" name="xlarge" label="Extra large" size="xlarge" checked /></div>),
  entry("file-upload", "FileUpload", "FORM", "A native file upload with four sizes, visual drop zone, accept filter, hint, and multiple selection.", "file upload attachment dropzone size", [["id / name / label", "string", "required"], ["size", "ControlSize", '"medium"'], ["accept / multiple", "string / boolean", "— / false"]], `<FileUpload id="avatar" name="avatar" label="Upload avatar" size="large" accept="image/*" />`, () => <FileUpload id="component-upload" name="files" label="Choose files or drag them here" size="large" accept="image/*,.pdf" hint="PNG, JPG, or PDF up to 10 MB" multiple />),
  entry("form-field", "FormField", "FORM", "Semantically connects a label, hint, required marker, control, and error.", "label hint error aria", [["label / htmlFor", "string", "required"], ["hint / error", "string", "—"], ["required", "boolean", "false"]], `<FormField label="Email" htmlFor="email" hint="Work email" required>\n  <Input id="email" name="email" type="email" />\n</FormField>`, () => <FormField label="Email address" htmlFor="field-demo" hint="We never share your email." error="Enter a valid email address." required><Input id="field-demo" name="email" type="email" value="invalid" aria-invalid="true" aria-describedby="field-demo-error" /></FormField>),
  entry("alert", "Alert", "FEEDBACK", "A status message with an automatic role; errors use alert, while other variants use status.", "info success warning error", [["variant", '"info" | "success" | "warning" | "error"', '"info"'], ["children", "CocoNode", "—"]], `<Alert variant="success">Changes saved.</Alert>`, () => <Stack gap="small"><Alert>Deployment is processing.</Alert><Alert variant="success">Changes saved.</Alert><Alert variant="warning">Review your input.</Alert><Alert variant="error">Request failed.</Alert></Stack>),
  entry("badge", "Badge", "FEEDBACK", "A compact status label with six consistent visual tones.", "pill label status chip info", [["variant", '"neutral" | "primary" | "success" | "warning" | "danger" | "info"', '"neutral"'], ["children", "CocoNode", "—"]], `<Badge variant="success">Active</Badge>`, () => <Inline gap="small"><Badge>Neutral</Badge><Badge variant="primary">Primary</Badge><Badge variant="success">Success</Badge><Badge variant="warning">Warning</Badge><Badge variant="danger">Error</Badge><Badge variant="info">Info</Badge></Inline>),
  entry("progress", "Progress", "FEEDBACK", "A native progress bar with a label, safe value bounds, and visual value.", "loading completion meter", [["value", "number", "required"], ["max", "number", "100"], ["label", "string", "required"]], `<Progress value={72} max={100} label="Upload progress" />`, () => <Progress value={72} label="Project completion" />),
  entry("spinner", "Spinner", "FEEDBACK", "A loading indicator in four sizes with a screen-reader label and reduced-motion behavior.", "loading pending busy size", [["size", "ControlSize", '"medium"'], ["label", "string", '"Loading"']], `<Spinner size="xlarge" label="Loading report" />`, () => <Inline gap="large" align="end"><Spinner size="small" label="Small loading" /><Spinner label="Medium loading" /><Spinner size="large" label="Large loading" /><Spinner size="xlarge" label="Extra large loading" /></Inline>),
  entry("skeleton", "Skeleton", "FEEDBACK", "A CSP-safe loading placeholder with typed size tokens and reduced-motion fallback.", "loading placeholder shimmer csp", [["width", "SkeletonWidth", '"full"'], ["height", "SkeletonHeight", '"body"'], ["radius", '"small" | "medium" | "large" | "full"', '"medium"']], `<Skeleton width="three-quarter" height="heading" />`, () => <Stack gap="small"><Skeleton width="half" height="heading" /><Skeleton height="text" /><Skeleton width="three-quarter" height="text" /><Inline gap="small"><Skeleton width="avatar" height="avatar" radius="full" /><Skeleton width="half" height="avatar" /></Inline></Stack>),
  entry("empty-state", "EmptyState", "FEEDBACK", "A consistent empty state with an icon, title, description, and optional action.", "empty no data zero state", [["title", "string", "required"], ["description", "string", "—"], ["icon / action", "CocoNode", "—"]], `<EmptyState icon={<BoxMinimalisticIcon size={32} />} title="No projects yet" description="Create your first project." action={<Button>Create project</Button>} />`, () => <EmptyState icon={<BoxMinimalisticIcon size={34} />} title="No projects yet" description="Create your first CocoFrame project to see it here." action={<Button>Create project</Button>} />),
  entry("toast", "Toast", "FEEDBACK", "A concise notification with semantic status/alert behavior, four variants, an action, and a dismiss control.", "toast notification snackbar feedback", [["title", "string", "required"], ["variant", '"info" | "success" | "warning" | "error"', '"info"'], ["action / onDismiss", "CocoNode / handler", "—"]], `<Toast variant="success" title="Project saved" description="Your changes are live." />`, () => <Toast variant="success" title="Project saved" description="Your changes are now live." action={<a href="#toast">View</a>} />),
  entry("toaster", "Toaster", "FEEDBACK", "A live region and positioned container for displaying one or more Toast components from an island.", "toaster notifications live region queue", [["position", '"top-right" | "top-center" | "bottom-right" | "bottom-center"', '"bottom-right"'], ["label", "string", '"Notifications"'], ["children", "Toast[]", "—"]], `<Toaster position="bottom-right">\n  <Toast title="Saved" variant="success" />\n</Toaster>`, (context) => <Stack gap="small"><Button onClick={context.showToast}>Show toast</Button><Text size="small" tone="muted">Click to test the live notification.</Text>{context.toastVisible ? <Toaster><Toast variant="success" title="Changes saved" description="The component catalog is up to date." onDismiss={context.hideToast} /></Toaster> : null}</Stack>),
  entry("card", "Card", "DATA DISPLAY", "A lightweight content surface that can use an article, section, or div element.", "surface panel article", [["as", '"article" | "section" | "div"', '"article"'], ["children", "CocoNode", "—"]], `<Card as="section"><Heading level={3}>Status</Heading><Text>Operational</Text></Card>`, () => <Card as="section"><Stack gap="small"><Badge variant="success">Operational</Badge><Heading level={3} size="small">Project status</Heading><Text tone="muted" size="small">All systems are running normally.</Text></Stack></Card>),
  entry("avatar", "Avatar", "DATA DISPLAY", "An image avatar or initials fallback with four consistent sizes and an accessible name.", "profile image initials user size", [["src / alt", "string", "—"], ["initials", "string", '"?"'], ["size", "ControlSize", '"medium"']], `<Avatar initials="RA" alt="Raka Aditya" size="xlarge" />`, () => <Inline gap="medium" align="end"><Avatar initials="S" alt="Small" size="small" /><Avatar initials="M" alt="Medium" /><Avatar initials="L" alt="Large" size="large" /><Avatar initials="XL" alt="Extra large" size="xlarge" /></Inline>),
  entry("stat", "Stat", "DATA DISPLAY", "A compact metric card with a label, value, trend, and semantic tone.", "metric kpi analytics number", [["label", "string", "required"], ["value", "CocoNode", "required"], ["trend / tone", "string / tone", "— / neutral"]], `<Stat label="Monthly revenue" value="$24,500" trend="↑ 12.5%" tone="positive" />`, () => <Grid columns={2} gap="small"><Stat label="Active users" value="12.4k" trend="↑ 8.2%" tone="positive" /><Stat label="Bounce rate" value="21%" trend="↓ 3.1%" tone="positive" /></Grid>),
  entry("table", "Table", "DATA DISPLAY", "A responsive table with a caption, scoped headers, and optional striped rows.", "rows columns data responsive", [["headers", "readonly CocoNode[]", "required"], ["rows", "readonly CocoNode[][]", "required"], ["caption / striped", "string / boolean", "— / false"]], `<Table caption="Deployments" headers={["Name", "Status"]} rows={[["Web", "Ready"]]} striped />`, () => <Table caption="Recent deployments" headers={["Service", "Status", "Region"]} rows={[["Web", <Badge variant="success">Ready</Badge>, "SIN"], ["API", <Badge variant="warning">Building</Badge>, "JKT"]]} striped />),
  entry("stack", "Stack", "LAYOUT", "A vertical layout primitive with consistent gaps and semantic element options.", "column gap spacing", [["gap", '"small" | "medium" | "large"', '"medium"'], ["as", '"div" | "section" | "main" | "form"', '"div"']], `<Stack as="section" gap="large"><Card>First</Card><Card>Second</Card></Stack>`, () => <Stack gap="small"><Card>First item</Card><Card>Second item</Card><Card>Third item</Card></Stack>),
  entry("container", "Container", "LAYOUT", "A page-width constraint with responsive gutters and four size options.", "wrapper max width center", [["size", '"small" | "medium" | "large" | "full"', '"large"'], ["as", '"div" | "section" | "main"', '"div"']], `<Container size="medium"><Heading>Centered content</Heading></Container>`, () => <Container size="small" class="component-mini-surface"><Text size="small" tone="muted">This content is constrained by a small Container.</Text></Container>),
  entry("grid", "Grid", "LAYOUT", "A 1–4 column CSS Grid that automatically becomes one column on mobile.", "columns responsive cards", [["columns", "1 | 2 | 3 | 4", "2"], ["gap", '"small" | "medium" | "large"', '"medium"'], ["as", '"div" | "section" | "ul"', '"div"']], `<Grid columns={3} gap="large"><Card>A</Card><Card>B</Card><Card>C</Card></Grid>`, () => <Grid columns={3} gap="small"><Card>A</Card><Card>B</Card><Card>C</Card></Grid>),
  entry("inline", "Inline", "LAYOUT", "A flex row for actions and metadata with alignment, distribution, and wrapping.", "row flex align justify wrap", [["gap", '"small" | "medium" | "large"', '"medium"'], ["align / justify", "enum", '"center" / "start"'], ["wrap", "boolean", "true"]], `<Inline justify="between"><Text>Profile</Text><Button>Edit</Button></Inline>`, () => <Inline justify="between"><Inline gap="small"><Avatar initials="CF" alt="CocoFrame" size="small" /><Text>cocoframe</Text></Inline><Badge variant="success">Online</Badge></Inline>),
  entry("divider", "Divider", "LAYOUT", "A horizontal, vertical, or labeled separator with separator semantics.", "hr separator line", [["orientation", '"horizontal" | "vertical"', '"horizontal"'], ["label", "string", "—"]], `<Divider />\n<Divider label="or continue with" />`, () => <Stack gap="small"><Text size="small">First section</Text><Divider label="or continue with" /><Text size="small">Second section</Text></Stack>),
  entry("heading", "Heading", "TYPOGRAPHY", "An h1–h6 heading with semantic level separated from visual size.", "h1 h2 title level size", [["level", "1 | 2 | 3 | 4 | 5 | 6", "2"], ["size", '"small" | "medium" | "large" | "xlarge"', '"large"']], `<Heading level={1} size="xlarge">Build faster.</Heading>`, () => <Stack gap="small"><Heading level={3} size="large">Build faster.</Heading><Heading level={4} size="small">Keep the HTML semantic.</Heading></Stack>),
  entry("text", "Text", "TYPOGRAPHY", "Body text with explicit element, size, and tone.", "paragraph span muted danger success", [["as", '"p" | "span" | "small" | "strong"', '"p"'], ["tone", '"default" | "muted" | "danger" | "success"', '"default"'], ["size", '"small" | "medium" | "large"', '"medium"']], `<Text tone="muted" size="small">Last updated today.</Text>`, () => <Stack gap="small"><Text size="large">Default body copy</Text><Text tone="muted">Muted supporting text</Text><Text tone="success" size="small">Everything is operational</Text></Stack>),
  entry("code", "Code", "TYPOGRAPHY", "Inline and block code without a syntax-highlighter runtime.", "pre monospace snippet", [["block", "boolean", "false"], ["children", "CocoNode", "—"]], `<Text>Run <Code>npm run dev</Code></Text>\n<Code block>{source}</Code>`, () => <Stack gap="small"><Text>Run <Code>npm run dev</Code> to start.</Text><Code block>{`import { Button } from "@cocoframe/ui";`}</Code></Stack>),
  entry("syntax-highlighter", "SyntaxHighlighter", "TYPOGRAPHY", "Server-first syntax highlighting for TSX, TypeScript, JavaScript, JSON, CSS, HTML, Bash, and plain text.", "code syntax highlighting lexer line numbers server first", [["code", "string", "required"], ["language", "SyntaxLanguage", '"tsx"'], ["showLineNumbers", "boolean", "false"], ["label / class", "string", "—"]], `<SyntaxHighlighter\n  code={'const ready = true;'}\n  language="typescript"\n  showLineNumbers\n/>`, () => <SyntaxHighlighter code={`import { definePage } from "@cocoframe/core";\n\nexport default definePage({\n  meta: { title: "Hello" },\n  view: () => <h1>Hello CocoFrame</h1>,\n});`} language="tsx" label="CocoFrame page example" showLineNumbers />),
  entry("breadcrumb", "Breadcrumb", "NAVIGATION", "A nav/ol-based page trail with aria-current on the active page.", "path crumbs hierarchy", [["items", "readonly BreadcrumbItem[]", "required"], ["label", "string", '"Breadcrumb"']], `<Breadcrumb items={[{ label: "Home", href: "/" }, { label: "Docs" }]} />`, () => <Breadcrumb items={[{ label: "Home", href: "/" }, { label: "Docs", href: "/docs" }, { label: "Components" }]} />),
  entry("pagination", "Pagination", "NAVIGATION", "Server-friendly page navigation that produces standard URLs and aria-current.", "pages next previous list", [["current / total", "number", "required"], ["basePath", "string", '""'], ["label", "string", '"Pagination"']], `<Pagination current={2} total={5} basePath="/articles" />`, () => <Pagination current={2} total={5} basePath="/components" />),
  entry("site-header", "SiteHeader", "NAVIGATION", "A ready-to-use header with standard, centered, and split variants, sticky mode, actions, and a mobile menu slot.", "header navbar centered split responsive sticky", [["brand", "CocoNode", "required"], ["variant", '"standard" | "centered" | "split"', '"standard"'], ["items / actions / menuButton", "navigation slots", "—"]], `<SiteHeader brand="Acme" variant="split" items={navigation} actions={<Button>Sign in</Button>} menuButton={<IconButton label="Open menu"><HamburgerMenuIcon size={20} /></IconButton>} />`, () => <div class="component-header-showcase"><SiteHeader brand="coco" variant="standard" items={[{ label: "Home", href: "#site-header", current: true }, { label: "Docs", href: "#site-header" }]} actions={<Button size="small">Start</Button>} /><SiteHeader brand="coco" variant="centered" items={[{ label: "Product", href: "#site-header" }, { label: "Templates", href: "#site-header" }]} actions={<IconButton label="Account" size="small"><UserIcon size={17} /></IconButton>} /><SiteHeader brand="coco" variant="split" items={[{ label: "Features", href: "#site-header" }, { label: "About", href: "#site-header" }]} menuButton={<IconButton label="Open menu" onClick={() => openNativeDialog("header-offcanvas")}><HamburgerMenuIcon size={20} /></IconButton>} /><Offcanvas id="header-offcanvas" title="Navigation" footer={<Button variant="secondary" onClick={() => closeNativeDialog("header-offcanvas")}>Close</Button>}><nav class="component-offcanvas-nav"><a href="#site-header">Home</a><a href="#site-header">Features</a><a href="#site-header">Templates</a><a href="#site-header">Docs</a></nav></Offcanvas></div>),
  entry("mega-menu", "MegaMenu", "NAVIGATION", "Progressive mega navigation with grouped links, icon slots, featured content, and three alignments.", "mega menu navigation groups featured", [["label / groups", "string / MegaMenuGroup[]", "required"], ["featured", "CocoNode", "—"], ["align / open", '"start" | "center" | "end" / boolean', '"center" / false']], `<MegaMenu label="Products" groups={[{ title: "Build", items: products }]} featured={<Card>New release</Card>} />`, () => <MegaMenu label="Explore products" open align="start" groups={[{ title: "Build", items: [{ label: "Web Apps", href: "#mega-menu", description: "Server-first applications", icon: <Widget4Icon size={20} /> }, { label: "API", href: "#mega-menu", description: "Typed endpoints", icon: <CodeSquareIcon size={20} /> }] }, { title: "Learn", items: [{ label: "Documentation", href: "#mega-menu", description: "Guides and references", icon: <DocumentIcon size={20} /> }, { label: "Templates", href: "#mega-menu", description: "Start from a pattern", icon: <FolderIcon size={20} /> }] }]} featured={<Stack gap="small"><Badge variant="primary">New</Badge><Heading level={3} size="small">CocoFrame 1.0</Heading><Text size="small" tone="muted">Explore the latest components.</Text></Stack>} />),
  entry("tabs", "Tabs", "NAVIGATION", "An accessible tablist with a controlled active panel; dynamic interaction activates when used in an island.", "tabs tablist panels navigation", [["id / items", "string / readonly TabItem[]", "required"], ["activeId", "string", "first enabled"], ["onActivate", "(id) => void", "—"]], `<Tabs id="settings" items={tabs} activeId={activeTab} onActivate={setActiveTab} />`, (context) => <Tabs id="component-tabs" activeId={context.activeTab} onActivate={context.activateTab} items={[{ id: "overview", label: "Overview", panel: <Text tone="muted">Project overview and recent activity.</Text> }, { id: "members", label: "Members", panel: <Text tone="muted">Manage members and permissions.</Text> }, { id: "billing", label: "Billing", panel: <Text tone="muted">Billing details and invoices.</Text> }]} />),
  entry("dropdown-menu", "DropdownMenu", "NAVIGATION", "A progressive action menu based on details/summary that still works without JavaScript.", "dropdown menu actions details", [["label", "string", "required"], ["items", "readonly DropdownMenuItem[]", "required"], ["align / open", "enum / boolean", '"start" / false']], `<DropdownMenu label="Project actions" items={[{ label: "Settings", href: "/settings" }]} />`, () => <DropdownMenu label="Project actions" open items={[{ label: "Open project", href: "#dropdown-menu", description: "View project dashboard" }, { label: "Duplicate", href: "#dropdown-menu", description: "Create a copy" }, { label: "Delete", href: "#dropdown-menu", danger: true }]} />),
  entry("tooltip", "Tooltip", "NAVIGATION", "Contextual information that appears on hover or keyboard focus without a JavaScript runtime.", "tooltip hint hover focus", [["id / content", "string", "required"], ["placement", '"top" | "right" | "bottom" | "left"', '"top"'], ["children", "CocoNode", "required"]], `<Tooltip id="publish-help" content="Visible to everyone"><IconButton label="About publishing"><QuestionCircleIcon size={19} /></IconButton></Tooltip>`, () => <Inline justify="center"><Tooltip id="component-tooltip" content="Keyboard and hover accessible" placement="top"><IconButton label="More information" variant="secondary"><QuestionCircleIcon size={19} /></IconButton></Tooltip></Inline>),
  entry("details", "Details", "DISCLOSURE", "Interactive disclosure based on the native details element—without JavaScript hydration.", "accordion faq summary native", [["summary", "string", "required"], ["open", "boolean", "false"], ["children", "CocoNode", "—"]], `<Details summary="Does this need JavaScript?">No. It uses native HTML.</Details>`, () => <Details summary="Does this component need JavaScript?" open>No. The browser handles the native details element.</Details>),
  entry("dialog", "Dialog", "OVERLAY", "A native modal with connected title/description, three sizes, body content, and footer actions.", "dialog modal overlay confirmation", [["id / title", "string", "required"], ["description / footer", "string / CocoNode", "—"], ["size", '"small" | "medium" | "large"', '"medium"']], `<Button onClick={() => document.querySelector("#confirm")?.showModal()}>Open dialog</Button>\n<Dialog id="confirm" title="Publish project">...</Dialog>`, () => <><Button onClick={() => openNativeDialog("component-dialog")}>Open modal</Button><Dialog id="component-dialog" title="Publish this project?" description="The latest version will become visible to everyone." footer={<><Button variant="secondary" onClick={() => closeNativeDialog("component-dialog")}>Cancel</Button><Button onClick={() => closeNativeDialog("component-dialog")}>Publish</Button></>}><Alert variant="info">You can unpublish the project later.</Alert></Dialog></>),
  entry("bottom-sheet", "BottomSheet", "OVERLAY", "A mobile dialog that rises from the bottom with a handle, scrollable content, and a safe action area.", "bottom sheet mobile drawer overlay", [["id / title", "string", "required"], ["description / footer", "string / CocoNode", "—"], ["open", "boolean", "false"]], `<Button onClick={() => document.querySelector("#filters")?.showModal()}>Filters</Button>\n<BottomSheet id="filters" title="Filter results">...</BottomSheet>`, () => <><Button variant="secondary" onClick={() => openNativeDialog("component-bottom-sheet")}>Open bottom sheet</Button><BottomSheet id="component-bottom-sheet" title="Filter projects" description="Choose filters, then apply your selection." footer={<><Button variant="secondary" onClick={() => closeNativeDialog("component-bottom-sheet")}>Reset</Button><Button onClick={() => closeNativeDialog("component-bottom-sheet")}>Apply filters</Button></>}><Stack gap="medium"><Checkbox id="sheet-active" name="active" label="Active projects" checked /><Checkbox id="sheet-shared" name="shared" label="Shared with me" /><RadioGroup id="sheet-sort" name="sort" legend="Sort by" value="updated" options={[{ label: "Recently updated", value: "updated" }, { label: "Name", value: "name" }]} /></Stack></BottomSheet></>),
  entry("offcanvas", "Offcanvas", "OVERLAY", "A native navigation drawer from the left or right with a header, scrollable body, footer, and accessible labeling.", "offcanvas offside sidebar drawer mobile navigation", [["id / title", "string", "required"], ["side", '"left" | "right"', '"left"'], ["description / footer", "string / CocoNode", "—"]], `<Button onClick={() => document.querySelector("#mobile-nav")?.showModal()}>Open menu</Button>\n<Offcanvas id="mobile-nav" title="Navigation" side="right">...</Offcanvas>`, () => <><Inline gap="small"><Button onClick={() => openNativeDialog("component-offcanvas-left")}>Open left</Button><Button variant="secondary" onClick={() => openNativeDialog("component-offcanvas-right")}>Open right</Button></Inline><Offcanvas id="component-offcanvas-left" title="Navigation" description="Browse the CocoFrame website." footer={<Button variant="secondary" onClick={() => closeNativeDialog("component-offcanvas-left")}>Close</Button>}><nav class="component-offcanvas-nav"><a href="#offcanvas">Home</a><a href="#offcanvas">Features</a><a href="#offcanvas">Components</a><a href="#offcanvas">Templates</a></nav></Offcanvas><Offcanvas id="component-offcanvas-right" title="Account" side="right" footer={<Button variant="secondary" onClick={() => closeNativeDialog("component-offcanvas-right")}>Close</Button>}><Stack><Text>Signed in as Raka</Text><Button variant="ghost">Account settings</Button></Stack></Offcanvas></>),
  entry("visually-hidden", "VisuallyHidden", "ACCESSIBILITY", "Screen-reader-only text that does not affect the visual layout.", "sr only accessible label", [["children", "CocoNode", "required"], ["class", "string", "—"]], `<Button aria-label="Open settings"><SettingsIcon size={19} /><VisuallyHidden>Open settings</VisuallyHidden></Button>`, () => <Inline gap="medium"><Button aria-label="Open settings"><SettingsIcon size={19} /> <VisuallyHidden>Open settings</VisuallyHidden></Button><Text tone="muted" size="small">The accessible name remains available to screen readers.</Text></Inline>),
  entry("solar-icons", "SolarIcon", "ICONOGRAPHY", "A complete collection of 1,246 typed, server-first Solar Linear icons that use currentColor and can be imported individually.", "solar icons home bell calendar camera chat document folder heart magnifier settings star user", [["size", "number", "24"], ["color", "string", '"currentColor"'], ["strokeWidth", "1 | 1.5 | 2", "1.5"], ["label / mirrored / class", "string / boolean / string", "— / false / —"]], `import HomeIcon from "@cocoframe/icons/linear/home";\n\n<HomeIcon label="Home" size={24} />\n<HomeIcon size={32} color="#1e7a5a" strokeWidth={2} />`, () => <div class="solar-icon-grid">{[{ name: "home", Icon: HomeIcon }, { name: "bell", Icon: BellIcon }, { name: "calendar", Icon: CalendarIcon }, { name: "camera", Icon: CameraIcon }, { name: "chat-round", Icon: ChatRoundIcon }, { name: "document", Icon: DocumentIcon }, { name: "folder", Icon: FolderIcon }, { name: "heart", Icon: HeartIcon }, { name: "magnifier", Icon: MagnifierIcon }, { name: "settings", Icon: SettingsIcon }, { name: "star", Icon: StarIcon }, { name: "user", Icon: UserIcon }].map(({ name, Icon }) => <span><Icon size={28} /><small>{name}</small></span>)}</div>, `import HomeIcon from "@cocoframe/icons/linear/home"`),
  entry("accordion", "Accordion", "DISCLOSURE", "A collection of native disclosures with single or multiple modes and typed initial state.", "accordion faq details disclosure", [["id / items", "string / AccordionItem[]", "required"], ["multiple", "boolean", "false"], ["openIds", "readonly string[]", "[]"]], `<Accordion id="faq" items={questions} openIds={["shipping"]} />`, () => <Accordion id="demo-faq" openIds={["server"]} items={[{ id: "server", title: "Server-first?", content: "Yes, the HTML works immediately without JavaScript." }, { id: "mobile", title: "Mobile-ready?", content: "Responsive from 320px." }, { id: "ai", title: "AI-friendly?", content: "Typed and explicit APIs." }]} />),
  entry("alert-dialog", "AlertDialog", "OVERLAY", "A high-risk confirmation dialog with alertdialog role and separate actions.", "alert dialog confirm destructive", [["id / title / description", "string", "required"], ["cancel / action", "CocoNode", "—"], ["open", "boolean", "false"]], `<AlertDialog id="delete" title="Delete project?" description="This cannot be undone." />`, () => <><Button variant="danger" onClick={() => openNativeDialog("catalog-alert-dialog")}>Delete project</Button><AlertDialog id="catalog-alert-dialog" title="Delete project?" description="This action cannot be undone." cancel={<Button variant="secondary" onClick={() => closeNativeDialog("catalog-alert-dialog")}>Cancel</Button>} action={<Button variant="danger" onClick={() => closeNativeDialog("catalog-alert-dialog")}>Delete</Button>} /></>),
  entry("aspect-ratio", "AspectRatio", "LAYOUT", "A media container with typed ratios, no inline styles, and no layout shift.", "aspect ratio media video image", [["ratio", '"square" | "video" | "portrait" | "wide"', '"video"'], ["children", "CocoNode", "—"]], `<AspectRatio ratio="video"><img src="/cover.jpg" alt="" /></AspectRatio>`, () => <AspectRatio ratio="video"><div class="component-mini-surface"><Heading level={3} size="small">16:9 media</Heading></div></AspectRatio>),
  entry("attachment", "Attachment", "DATA DISPLAY", "A ready-to-use file list with metadata, status, links, and an action slot.", "attachment files upload list", [["items", "readonly AttachmentItem[]", "required"], ["label", "string", '"Attachments"']], `<Attachment items={[{ name: "report.pdf", meta: "2.4 MB", status: "ready" }]} />`, () => <Attachment items={[{ name: "brand-guidelines.pdf", meta: "2.4 MB · PDF", href: "#attachment" }, { name: "hero-image.png", meta: "Uploading · 64%", status: "uploading" }]} />),
  entry("bubble", "Bubble", "AI & CHAT", "An incoming/outgoing conversation bubble with sender and timestamp.", "chat bubble conversation ai", [["side", '"incoming" | "outgoing"', '"incoming"'], ["sender / timestamp", "string", "—"]], `<Bubble side="outgoing" timestamp="10:42">Ship it.</Bubble>`, () => <Stack gap="small"><Bubble sender="Coco AI" timestamp="10:41">The framework is ready to test.</Bubble><Bubble side="outgoing" timestamp="10:42">Ship it.</Bubble></Stack>),
  entry("button-group", "ButtonGroup", "ACTION", "Groups related buttons with a group role and typed orientation.", "button group toolbar segmented", [["orientation", '"horizontal" | "vertical"', '"horizontal"'], ["label", "string", '"Actions"']], `<ButtonGroup><Button>Save</Button><Button variant="secondary">Preview</Button></ButtonGroup>`, () => <ButtonGroup label="Editor actions"><Button>Save</Button><Button variant="secondary">Preview</Button><Button variant="secondary">Share</Button></ButtonGroup>),
  entry("calendar", "Calendar", "DATE & TIME", "A server-rendered monthly calendar with standard form-based date selection.", "calendar month date days", [["id / year / month", "string / number", "required"], ["selected", "ISO date string", "—"]], `<Calendar id="date" year={2026} month={8} selected="2026-08-21" />`, () => <Calendar id="catalog-date" year={2026} month={8} selected="2026-08-21" />),
  entry("carousel", "Carousel", "DATA DISPLAY", "A scroll-snap carousel that remains navigable with anchors and no JavaScript runtime.", "carousel slider cards scroll snap", [["id / items", "string / CarouselItem[]", "required"], ["label", "string", '"Carousel"']], `<Carousel id="features" items={slides} />`, () => <Carousel id="catalog-carousel" items={[{ id: "one", content: <Card><Heading level={3} size="small">Fast</Heading><Text size="small">Server-first rendering.</Text></Card> }, { id: "two", content: <Card><Heading level={3} size="small">Typed</Heading><Text size="small">Predictable component APIs.</Text></Card> }]} />),
  entry("chart", "Chart · Line & Area", "DATA DISPLAY", "Server-first SVG line and area charts with multiple datasets, grid, legend, value labels, and a hidden data table for screen readers.", "chart line area graph trend analytics svg", [["type", "ChartType", '"bar"'], ["labels / datasets", "string[] / ChartDataset[]", "—"], ["showLegend / showGrid / showValues", "boolean", "auto / true / false"], ["aspect", '"wide" | "standard" | "square"', '"wide"']], `<Chart type="line" label="Traffic trend" labels={months} datasets={series} />\n<Chart type="area" label="Conversion trend" labels={months} datasets={series} />`, () => <div class="component-chart-showcase"><Chart type="line" label="Traffic trend" description="Requests and conversions over six months." labels={chartLabels} datasets={chartSeries} /><Chart type="area" label="Conversion area" labels={chartLabels} datasets={[{ ...chartSeries[0], fill: true }]} /></div>, `import { Chart } from "@cocoframe/ui"`),
  entry("chart-bars", "Chart · Bars", "DATA DISPLAY", "Grouped, horizontal, and stacked bar charts with negative values, automatic scaling, and an optional number formatter.", "chart bar grouped horizontal stacked comparison", [["type", '"bar" | "horizontal-bar" | "stacked-bar"', '"bar"'], ["min / max", "number", "auto"], ["formatValue", "(value: number) => string", "Intl.NumberFormat"], ["showValues", "boolean", "false"]], `<Chart type="bar" label="Monthly traffic" labels={months} datasets={series} />\n<Chart type="horizontal-bar" label="Channel performance" labels={channels} datasets={series} />\n<Chart type="stacked-bar" label="Usage by plan" labels={months} datasets={series} />`, () => <div class="component-chart-showcase"><Chart type="bar" label="Grouped bars" labels={chartLabels} datasets={chartSeries} showValues /><Chart type="horizontal-bar" label="Horizontal bars" labels={["Web", "API", "Worker", "Mobile"]} datasets={[{ label: "Requests", data: [84, 62, 47, 71] }]} /><Chart type="stacked-bar" label="Stacked usage" labels={chartLabels} datasets={chartSeries} /></div>, `import { Chart } from "@cocoframe/ui"`),
  entry("chart-radial", "Chart · Radial", "DATA DISPLAY", "Pie, multi-ring doughnut, and polar-area charts with colored categories, legends, and native SVG tooltips.", "chart pie doughnut donut polar radial distribution", [["type", '"pie" | "doughnut" | "polar-area"', "required"], ["labels / datasets", "string[] / ChartDataset[]", "required"], ["showLegend", "boolean", "true"], ["showValues", "boolean", "false"]], `<Chart type="pie" label="Traffic sources" labels={sources} datasets={breakdown} />\n<Chart type="doughnut" label="Acquisition mix" labels={sources} datasets={breakdown} />\n<Chart type="polar-area" label="Channel reach" labels={sources} datasets={breakdown} />`, () => <div class="component-chart-showcase"><Chart type="pie" label="Traffic sources" labels={chartBreakdownLabels} datasets={chartBreakdown} showValues /><Chart type="doughnut" label="Acquisition mix" labels={chartBreakdownLabels} datasets={[...chartBreakdown, { label: "Previous", data: [42, 31, 19, 8] }]} /><Chart type="polar-area" label="Channel reach" labels={chartBreakdownLabels} datasets={chartBreakdown} /></div>, `import { Chart } from "@cocoframe/ui"`),
  entry("chart-radar", "Chart · Radar", "DATA DISPLAY", "A radar chart for comparing multiple dimensions and datasets on one easy-to-scan scale.", "chart radar spider skills dimensions", [["type", '"radar"', "required"], ["labels / datasets", "string[] / ChartDataset[]", "required"], ["max", "number", "auto"], ["showGrid / showValues", "boolean", "true / false"]], `<Chart type="radar" label="Platform score" labels={dimensions} datasets={scores} max={100} />`, () => <Chart type="radar" label="Platform score" description="Web and mobile capability comparison." labels={["Speed", "SEO", "DX", "Mobile", "API", "A11y"]} datasets={[{ label: "CocoFrame", data: [94, 96, 91, 87, 95, 92] }, { label: "Baseline", data: [67, 71, 62, 74, 65, 69], tone: "slate" }]} max={100} />, `import { Chart } from "@cocoframe/ui"`),
  entry("chart-points", "Chart · Scatter & Bubble", "DATA DISPLAY", "Scatter and bubble charts accept typed x/y points; bubbles use a per-point radius for the third dimension.", "chart scatter bubble xy correlation distribution", [["type", '"scatter" | "bubble"', "required"], ["datasets[].data", "ChartPoint[]", "required"], ["ChartPoint", "{ x; y; r?; label? }", "—"], ["min / max", "number", "auto"]], `<Chart type="scatter" label="Latency correlation" datasets={points} />\n<Chart type="bubble" label="Segment opportunity" datasets={points} />`, () => <div class="component-chart-showcase"><Chart type="scatter" label="Latency correlation" datasets={chartPoints} /><Chart type="bubble" label="Segment opportunity" datasets={chartPoints} /></div>, `import { Chart } from "@cocoframe/ui"`),
  entry("chart-mixed", "Chart · Mixed", "DATA DISPLAY", "A mixed chart combines bars, lines, and areas in one plot through the type of each dataset.", "chart mixed combo bar line area datasets", [["type", '"mixed"', "required"], ["datasets[].type", '"bar" | "line" | "area"', '"line"'], ["datasets[].tone", "ChartTone", "automatic"], ["datasets[].fill", "boolean", "false"]], `<Chart type="mixed" label="Revenue and target" labels={months} datasets={[\n  { label: "Revenue", type: "bar", data: revenue },\n  { label: "Target", type: "line", data: target },\n]} />`, () => <Chart type="mixed" label="Revenue and target" description="Bars show actual revenue; the line shows the monthly target." labels={chartLabels} datasets={[{ label: "Revenue", type: "bar", data: [42, 56, 61, 74, 82, 96], tone: "primary" }, { label: "Target", type: "line", data: [48, 52, 58, 66, 76, 88], tone: "amber" }]} showValues />, `import { Chart } from "@cocoframe/ui"`),
  entry("collapsible", "Collapsible", "DISCLOSURE", "A single progressive disclosure with a summary and flexible content.", "collapsible expand disclosure", [["summary", "string", "required"], ["open", "boolean", "false"]], `<Collapsible summary="Advanced settings">...</Collapsible>`, () => <Collapsible summary="Advanced settings" open><Text size="small" tone="muted">Cache, middleware, and deployment options.</Text></Collapsible>),
  entry("combobox", "Combobox", "FORM", "A typed combobox with a searchable CocoFrame dropdown in an island and a native datalist as the server-first fallback.", "combobox autocomplete datalist search select", [["id / name / label", "string", "required"], ["options", "readonly ComboboxOption[]", "required"], ["interactive", "boolean", "false"], ["emptyText / onInput / onChange", "string / handlers", "—"]], `<Combobox\n  id="framework"\n  name="framework"\n  label="Framework"\n  options={options}\n  interactive\n/>`, () => <Combobox id="catalog-framework" name="framework" label="Choose framework" placeholder="Search a framework…" interactive options={[{ label: "CocoFrame", value: "cocoframe" }, { label: "Next.js", value: "nextjs" }, { label: "Nuxt", value: "nuxt" }]} />),
  entry("command", "Command", "NAVIGATION", "A command-palette shell with search, grouped actions, shortcuts, links, and disabled states.", "command palette search actions keyboard", [["id / groups", "string / CommandGroup[]", "required"], ["placeholder / emptyText", "string", "—"]], `<Command id="palette" groups={commands} />`, () => <Command id="catalog-command" groups={[{ label: "Navigation", items: [{ label: "Open documentation", description: "Browse framework guides", href: "/docs", shortcut: "⌘D" }, { label: "Browse icons", href: "/icons", shortcut: "⌘I" }] }, { label: "Project", items: [{ label: "Create page", shortcut: "⌘N" }, { label: "Delete project", disabled: true }] }]} />),
  entry("context-menu", "ContextMenu", "NAVIGATION", "A progressive action menu with a keyboard-accessible details fallback.", "context menu right click actions", [["label / items", "string / CommandItem[]", "required"], ["open", "boolean", "false"]], `<ContextMenu label="Card actions" items={actions}>Open actions</ContextMenu>`, () => <ContextMenu label="Card actions" open items={[{ label: "Open", href: "#context-menu" }, { label: "Duplicate" }, { label: "Archive" }]}>Click for context actions</ContextMenu>),
  entry("data-table", "DataTable", "DATA DISPLAY", "A server-friendly data table with typed columns, URL sorting, a caption, and aria-sort.", "data table sortable rows columns", [["columns / rows", "DataTableColumn[] / records", "required"], ["sortKey / sortDirection", "string / asc|desc", "—"], ["sortValue / onSort", "column accessor / callback", "—"]], `<DataTable
  caption="Users"
  columns={columns}
  rows={users}
  sortKey={sort.key}
  sortDirection={sort.direction}
  sortPath="/users"
  onSort={(key, direction) => setSort({ key, direction })}
/>`, (context) => <DataTable caption="Recent deployments" sortKey={context.dataTableSortKey} sortDirection={context.dataTableSortDirection} onSort={context.sortDataTable} sortPath="/components#data-table" columns={[{ key: "service", label: "Service", sortable: true }, { key: "status", label: "Status" }, { key: "region", label: "Region", sortable: true }]} rows={[{ service: "Web", status: <Badge variant="success">Ready</Badge>, region: "SIN" }, { service: "API", status: <Badge variant="warning">Building</Badge>, region: "JKT" }, { service: "Worker", status: <Badge variant="success">Ready</Badge>, region: "NRT" }]} />),
  entry("date-picker", "DatePicker", "DATE & TIME", "A native date input with min/max, control size, and a semantic label.", "date picker input calendar", [["id / name / label", "string", "required"], ["value / min / max", "ISO date string", "—"], ["size", "ControlSize", '"medium"']], `<DatePicker id="launch" name="launch" label="Launch date" />`, () => <DatePicker id="catalog-launch" name="launch" label="Launch date" value="2026-08-21" min="2026-01-01" />),
  entry("direction", "Direction", "LAYOUT", "An LTR, RTL, or auto text-direction boundary for international components.", "direction rtl ltr internationalization", [["dir", '"ltr" | "rtl" | "auto"', "required"], ["as", '"div" | "section" | "article"', '"div"']], `<Direction dir="rtl">مرحبا بك</Direction>`, () => <Direction dir="rtl"><Card><Heading level={3} size="small">مرحباً بك</Heading><Text size="small" tone="muted">واجهة تدعم اتجاه النص.</Text></Card></Direction>),
  entry("hover-card", "HoverCard", "OVERLAY", "A CSS-only preview card that opens on hover or keyboard focus.", "hover card preview focus", [["id / trigger", "string / CocoNode", "required"], ["placement", '"top" | "bottom"', '"bottom"']], `<HoverCard id="profile" trigger="@cocoframe">Profile preview</HoverCard>`, () => <HoverCard id="catalog-profile" trigger={<a href="#hover-card">@cocoframe</a>}><Stack gap="small"><Avatar initials="CF" alt="CocoFrame" /><strong>CocoFrame</strong><Text size="small" tone="muted">Fast, typed, server-first.</Text></Stack></HoverCard>),
  entry("input-otp", "InputOtp", "FORM", "A grouped OTP input with per-digit labels, a numeric keyboard, and an autocomplete hint.", "otp pin passcode verification", [["id / name / label", "string", "required"], ["length", "number", "6"], ["value", "string", '""']], `<InputOtp id="otp" name="otp" label="Verification code" length={6} />`, () => <InputOtp id="catalog-otp" name="otp" label="Verification code" value="248" />),
  entry("item", "Item", "DATA DISPLAY", "A generic content row with an icon, title, description, link, and action slot.", "item list row action", [["title", "string", "required"], ["description / icon / action / href", "slots", "—"]], `<Item title="Billing" description="Manage invoices" icon={<DocumentIcon size={20} />} href="/billing" />`, () => <Stack gap="small"><Item title="Documentation" description="Guides and API reference" icon={<DocumentIcon size={20} />} href="#item" action={<Badge>12</Badge>} /><Item title="Team members" description="Manage roles and invitations" icon={<UsersGroupRoundedIcon size={20} />} action={<Button size="small" variant="ghost">Open</Button>} /></Stack>),
  entry("kbd", "Kbd", "TYPOGRAPHY", "A keyboard-key hint with consistent styling and native kbd semantics.", "keyboard shortcut key", [["title", "string", "—"], ["children", "CocoNode", "required"]], `<Kbd>⌘</Kbd><Kbd>K</Kbd>`, () => <Inline gap="small"><Text size="small">Open command</Text><Kbd>⌘</Kbd><Kbd>K</Kbd></Inline>),
  entry("label", "Label", "FORM", "A reusable form label with an accessible required marker.", "label form required", [["for", "string", "required"], ["required", "boolean", "false"]], `<Label for="company" required>Company</Label>`, () => <Stack gap="small"><Label for="catalog-company" required>Company</Label><Input id="catalog-company" name="company" placeholder="CocoFrame Labs" /></Stack>),
  entry("marker", "Marker", "DATA DISPLAY", "A compact marker for locations, annotations, or statuses with semantic tones.", "marker annotation status location", [["tone", '"neutral" | "primary" | "success" | "warning" | "danger"', '"neutral"'], ["icon", "CocoNode", "—"]], `<Marker tone="success" icon={<MapPointIcon size={16} />}>Jakarta</Marker>`, () => <Inline gap="small"><Marker icon={<MapPointIcon size={16} />}>Jakarta</Marker><Marker tone="primary">Beta</Marker><Marker tone="success">Online</Marker><Marker tone="warning">Review</Marker></Inline>),
  entry("menubar", "Menubar", "NAVIGATION", "A progressive application menubar with groups, shortcuts, links, and actions.", "menubar desktop application menu", [["menus", "readonly MenubarMenu[]", "required"], ["label", "string", '"Application menu"']], `<Menubar menus={menus} />`, () => <Menubar menus={[{ label: "File", items: [{ label: "New page", shortcut: "⌘N" }, { label: "Open", shortcut: "⌘O" }] }, { label: "View", items: [{ label: "Components", href: "#menubar" }, { label: "Documentation", href: "/docs" }] }]} />),
  entry("message", "Message", "AI & CHAT", "An AI/user/system message with an avatar, metadata, content, and an action slot.", "message ai chat assistant user", [["author", "string", "required"], ["role", '"user" | "assistant" | "system"', '"assistant"'], ["avatar / timestamp / actions", "slots", "—"]], `<Message author="Coco AI" role="assistant">How can I help?</Message>`, () => <Message author="Coco AI" avatar={<Avatar initials="AI" alt="Coco AI" size="small" />} timestamp="just now" actions={<Button size="small" variant="ghost">Copy</Button>}><Text size="small">The new component is available and remains server-first.</Text></Message>),
  entry("message-scroller", "MessageScroller", "AI & CHAT", "A scrollable live conversation log with aria-live and busy state.", "message scroller conversation log ai", [["label", "string", '"Conversation"'], ["busy", "boolean", "false"]], `<MessageScroller><Message author="AI">Hello</Message></MessageScroller>`, () => <MessageScroller label="Demo conversation"><Bubble sender="Coco AI">What would you like to build?</Bubble><Bubble side="outgoing">Dashboard mobile-ready.</Bubble><Bubble sender="Coco AI">I will prepare the typed components.</Bubble></MessageScroller>),
  entry("navigation-menu", "NavigationMenu", "NAVIGATION", "A navigation menu with active links and grouped flyouts without requiring a runtime.", "navigation menu navbar flyout", [["items", "readonly NavigationMenuItem[]", "required"], ["label", "string", '"Primary"']], `<NavigationMenu items={navigation} />`, () => <NavigationMenu items={[{ label: "Overview", href: "#navigation-menu", current: true }, { label: "Products", items: [{ label: "Web framework", href: "#navigation-menu", description: "Server-first applications" }, { label: "UI library", href: "#navigation-menu", description: "Typed components" }] }, { label: "Docs", href: "/docs" }]} />),
  entry("popover", "Popover", "OVERLAY", "The native Popover API with a trigger, placement token, dialog label, and no custom JavaScript.", "popover floating overlay native", [["id / trigger / label", "string / CocoNode", "required"], ["placement", '"top" | "right" | "bottom" | "left"', '"bottom"']], `<Popover id="filters" trigger="Open filters" label="Filters">...</Popover>`, () => <Popover id="catalog-popover" trigger="Open popover" label="Project information"><Stack gap="small"><strong>CocoFrame project</strong><Text size="small" tone="muted">Server-rendered popover content.</Text></Stack></Popover>),
  entry("questionnaire", "Questionnaire", "FORM", "A multi-question choice form with fieldsets, legends, descriptions, and selected states.", "questionnaire survey choices form", [["name / questions", "string / QuestionnaireQuestion[]", "required"]], `<Questionnaire name="onboarding" questions={questions} />`, () => <Questionnaire name="catalog-survey" questions={[{ id: "goal", prompt: "What would you like to build?", value: "web", choices: [{ label: "Web application", value: "web", description: "SSR and typed APIs" }, { label: "Mobile client", value: "mobile", description: "Generated Fetch client" }] }]} />),
  entry("resizable", "Resizable", "LAYOUT", "A panel layout with an accessible separator and native resize enhancement.", "resizable panels split layout", [["panels", "readonly ResizablePanel[]", "required"], ["orientation", '"horizontal" | "vertical"', '"horizontal"']], `<Resizable panels={[{ id: "nav", content: <Sidebar /> }, { id: "main", content: page }]} />`, () => <Resizable panels={[{ id: "catalog-resize-left", content: <Text size="small">Navigation panel</Text>, min: "small" }, { id: "catalog-resize-main", content: <Text size="small">Main content panel</Text>, min: "medium" }]} />),
  entry("scroll-area", "ScrollArea", "LAYOUT", "A keyboard-focusable scrollable region with three height limits and a custom scrollbar.", "scroll area overflow container", [["size", '"small" | "medium" | "large"', '"medium"'], ["label", "string", '"Scrollable content"']], `<ScrollArea size="small">{longContent}</ScrollArea>`, () => <ScrollArea size="small" label="Framework features"><Stack gap="small">{["Server rendering", "Typed APIs", "Generated clients", "Islands", "SEO metadata", "Security middleware", "Database adapters", "UI primitives"].map((label) => <Item title={label} />)}</Stack></ScrollArea>),
  entry("sidebar", "Sidebar", "NAVIGATION", "A ready-to-use sidebar with brand, groups, current state, badges, compact mode, and footer.", "sidebar app navigation dashboard", [["groups", "readonly SidebarGroup[]", "required"], ["brand / footer", "CocoNode", "—"], ["compact", "boolean", "false"]], `<Sidebar brand="Acme" groups={navigation} />`, () => <Sidebar brand="cocoframe" groups={[{ label: "Workspace", items: [{ label: "Overview", href: "#sidebar", icon: <HomeIcon size={18} />, current: true }, { label: "Projects", href: "#sidebar", icon: <Widget4Icon size={18} />, badge: <Badge>8</Badge> }, { label: "Team", href: "#sidebar", icon: <UsersGroupRoundedIcon size={18} /> }] }, { label: "Settings", items: [{ label: "Preferences", href: "#sidebar", icon: <SettingsIcon size={18} /> }] }]} footer={<Text size="small" tone="muted">v0.0.3</Text>} />),
  entry("slider", "Slider", "FORM", "A native range control with a label, output, min/max/step, and design-token accent.", "slider range volume price", [["id / name / label", "string", "required"], ["value / min / max / step", "number", "0 / 0 / 100 / 1"], ["showValue", "boolean", "true"]], `<Slider id="volume" name="volume" label="Volume" value={64} />`, () => <Slider id="catalog-volume" name="volume" label="Volume" value={64} step={1} />),
  entry("toggle", "Toggle", "ACTION", "A pressed-state button with two variants, four sizes, a label, and an optional island handler.", "toggle pressed formatting action", [["pressed / disabled", "boolean", "false"], ["size", "ControlSize", '"medium"'], ["variant", '"default" | "outline"', '"default"']], `<Toggle pressed label="Bold">B</Toggle>`, () => <Inline gap="small"><Toggle pressed label="Bold"><strong>B</strong></Toggle><Toggle variant="outline" label="Italic"><em>I</em></Toggle><Toggle size="large" label="Underline">U</Toggle></Inline>),
  entry("toggle-group", "ToggleGroup", "ACTION", "A set of single/multiple toggles with an accessible group label and four sizes.", "toggle group segmented control", [["items", "readonly ToggleGroupItem[]", "required"], ["value", "string | string[]", "—"], ["multiple / size", "boolean / ControlSize", "false / medium"]], `<ToggleGroup items={alignments} value="left" label="Alignment" />`, () => <ToggleGroup label="Text alignment" value="left" items={[{ value: "left", label: "Left", content: <AlignLeftIcon size={18} /> }, { value: "center", label: "Center", content: <AlignHorizontalCenterIcon size={18} /> }, { value: "right", label: "Right", content: <AlignRightIcon size={18} /> }]} />),
];

const entries = sortComponentCatalogEntries(unorderedEntries);
const catalogCategories = Array.from(new Set(entries.map((item) => item.category)));

export default defineIsland<Record<string, never>>({
  name: "component-browser",
  setup: () => {
    const query = signal("");
    const category = signal("ALL");
    const activeTab = signal("overview");
    const toastVisible = signal(false);
    const dataTableSortKey = signal("service");
    const dataTableSortDirection = signal<"asc" | "desc">("asc");
    if (typeof document !== "undefined" && !document.documentElement.hasAttribute("data-coco-catalog-shortcut")) {
      document.documentElement.setAttribute("data-coco-catalog-shortcut", "true");
      document.addEventListener("keydown", (event: KeyboardEvent) => {
        if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "k") {
          event.preventDefault();
          document.getElementById("component-catalog-search")?.focus();
        }
      });
    }
    return () => {
      const normalized = query.value.trim().toLowerCase();
      const shown = entries.filter((item) => !normalized || `${item.name} ${item.category} ${item.description} ${item.keywords}`.toLowerCase().includes(normalized));
      const filtered = shown.filter((item) => category.value === "ALL" || item.category === category.value);
      const previewContext: PreviewContext = {
        activeTab: activeTab.value,
        toastVisible: toastVisible.value,
        dataTableSortKey: dataTableSortKey.value,
        dataTableSortDirection: dataTableSortDirection.value,
        activateTab: (id) => { activeTab.value = id; },
        showToast: () => { toastVisible.value = true; },
        hideToast: () => { toastVisible.value = false; },
        sortDataTable: (key, direction) => { dataTableSortKey.value = key; dataTableSortDirection.value = direction; },
      };
      return <section class="official-catalog" id="catalog">
        <div class="catalog-heading"><div><span class="eyebrow">OFFICIAL UI</span><h2>{entries.length} component references + 1,246 icons</h2><p>Every example is rendered with <code>@cocoframe/ui</code> and <code>@cocoframe/icons</code>; browser JavaScript is active only inside the island.</p></div><div class="component-catalog-controls"><label class="component-search"><span aria-hidden="true"><MagnifierIcon size={20} /></span><input id="component-catalog-search" type="search" value={query.value} placeholder="Search UI and icons..." aria-label="Search components and icons" onInput={(event: Event) => { query.value = (event.currentTarget as HTMLInputElement).value; }} /><kbd>Ctrl/⌘ K</kbd></label><label class="component-category-filter"><span>Category</span><Select id="component-catalog-category" name="category" value={category.value} onInput={(event: Event) => { category.value = (event.currentTarget as HTMLSelectElement).value; }}><option value="ALL">All categories</option>{catalogCategories.map((name) => <option value={name}>{name}</option>)}</Select></label></div></div>
        <div class="component-result-count" role="status">{filtered.length} of {entries.length} references</div>
        <div class="official-component-list">{filtered.map((item) => <ComponentReference entry={item} context={previewContext} />)}</div>
        {filtered.length === 0 ? <p class="components-empty">No matching components. Try “form”, “feedback”, “overlay”, or “navigation”.</p> : null}
      </section>;
    };
  },
});

function entry(id: string, name: string, category: string, description: string, keywords: string, props: ComponentEntry["props"], code: string, preview: (context: PreviewContext) => CocoNode, importCode?: string): ComponentEntry {
  return { id, name, category, description, keywords, props, code, preview, ...(importCode ? { importCode } : {}) };
}

function ComponentReference({ entry: item, context }: { readonly entry: ComponentEntry; readonly context: PreviewContext }) {
  return <article class="official-component" id={item.id}><header><div><span>{item.category}</span><h2>{item.name}</h2><p>{item.description}</p></div><code>{item.importCode ?? `import { ${item.name} } from "@cocoframe/ui"`}</code></header><div class="component-reference-grid"><section class="component-preview"><h3>Preview</h3><div class="component-preview-stage">{item.preview(context)}</div></section><section class="component-source"><h3>Usage</h3><SyntaxHighlighter code={item.code} language="tsx" label={`${item.name} usage example`} /></section></div><section class="component-props"><h3>Props</h3><div role="table" aria-label={`${item.name} props`}><div role="row"><strong>Prop</strong><strong>Type</strong><strong>Default</strong></div>{item.props.map(([name, type, defaultValue]) => <div role="row"><code>{name}</code><code>{type}</code><span>{defaultValue}</span></div>)}</div></section><a class="guide-top" href="#top">Back to top <span aria-hidden="true"><ArrowUpIcon size={14} /></span></a></article>;
}

function openNativeDialog(id: string): void {
  const dialog = document.getElementById(id) as HTMLDialogElement | null;
  if (dialog && !dialog.open) dialog.showModal();
}

function closeNativeDialog(id: string): void {
  const dialog = document.getElementById(id) as HTMLDialogElement | null;
  if (dialog?.open) dialog.close();
}
